export const categories = {
  cars: {
    label: 'Cars',
    fields: [
      { key: 'price', label: 'Price', title: 'Price (₹ lakh)', prefix: '₹', suffix: ' lakh', better: 'low' },
      { key: 'mileage', label: 'Mileage', title: 'Mileage (km/l)', suffix: ' km/l', better: 'high' },
      { key: 'engine', label: 'Engine', title: 'Engine (cc)', suffix: ' cc', better: 'high' },
      { key: 'power', label: 'Power', title: 'Power (bhp)', suffix: ' bhp', better: 'high' },
      { key: 'seats', label: 'Seats', title: 'Seats', suffix: '', better: 'high' },
      { key: 'boot', label: 'Boot space', title: 'Boot space (litres)', suffix: ' L', better: 'high' },
      { key: 'airbags', label: 'Airbags', title: 'Airbags', suffix: '', better: 'high' },
    ],
    items: [
      { id: 1, name: 'Maruti Swift', brand: 'Maruti', price: 6.5, mileage: 24.8, engine: 1197, power: 81, seats: 5, boot: 265, airbags: 6 },
      { id: 2, name: 'Hyundai Creta', brand: 'Hyundai', price: 11, mileage: 17.4, engine: 1497, power: 113, seats: 5, boot: 433, airbags: 6 },
      { id: 3, name: 'Tata Nexon', brand: 'Tata', price: 8, mileage: 17.4, engine: 1199, power: 118, seats: 5, boot: 382, airbags: 6 },
      { id: 4, name: 'Mahindra Thar Roxx', brand: 'Mahindra', price: 13, mileage: 15, engine: 1997, power: 160, seats: 5, boot: 447, airbags: 6 },
      { id: 5, name: 'Kia Seltos', brand: 'Kia', price: 11, mileage: 17, engine: 1497, power: 113, seats: 5, boot: 433, airbags: 6 },
      { id: 6, name: 'Honda City', brand: 'Honda', price: 12, mileage: 18.4, engine: 1498, power: 119, seats: 5, boot: 506, airbags: 6 },
      { id: 7, name: 'Maruti Brezza', brand: 'Maruti', price: 8.5, mileage: 17.4, engine: 1462, power: 102, seats: 5, boot: 328, airbags: 6 },
      { id: 8, name: 'Toyota Innova Hycross', brand: 'Toyota', price: 19, mileage: 21, engine: 1987, power: 184, seats: 7, boot: 300, airbags: 6 },
      { id: 9, name: 'Mahindra Scorpio N', brand: 'Mahindra', price: 13.5, mileage: 14, engine: 2198, power: 172, seats: 7, boot: 460, airbags: 6 },
      { id: 10, name: 'Hyundai Venue', brand: 'Hyundai', price: 8, mileage: 18, engine: 1197, power: 82, seats: 5, boot: 350, airbags: 6 },
    ],
  },

  bikes: {
    label: 'Bikes',
    fields: [
      { key: 'price', label: 'Price', title: 'Price (₹ lakh)', prefix: '₹', suffix: ' lakh', better: 'low' },
      { key: 'mileage', label: 'Mileage', title: 'Mileage (km/l)', suffix: ' km/l', better: 'high' },
      { key: 'engine', label: 'Engine', title: 'Engine (cc)', suffix: ' cc', better: 'high' },
      { key: 'power', label: 'Power', title: 'Power (bhp)', suffix: ' bhp', better: 'high' },
      { key: 'topSpeed', label: 'Top speed', title: 'Top speed (km/h)', suffix: ' km/h', better: 'high' },
      { key: 'weight', label: 'Weight', title: 'Weight (kg)', suffix: ' kg', better: 'low' },
      { key: 'tank', label: 'Fuel tank', title: 'Fuel tank (litres)', suffix: ' L', better: 'high' },
    ],
    items: [
      { id: 1, name: 'Royal Enfield Classic 350', brand: 'Royal Enfield', price: 1.95, mileage: 35, engine: 349, power: 20, topSpeed: 115, weight: 195, tank: 13 },
      { id: 2, name: 'Bajaj Pulsar NS200', brand: 'Bajaj', price: 1.5, mileage: 40, engine: 199, power: 24, topSpeed: 136, weight: 159, tank: 12 },
      { id: 3, name: 'KTM 390 Duke', brand: 'KTM', price: 3.1, mileage: 28, engine: 399, power: 45, topSpeed: 167, weight: 168, tank: 15 },
      { id: 4, name: 'TVS Apache RTR 160 4V', brand: 'TVS', price: 1.3, mileage: 45, engine: 160, power: 17, topSpeed: 114, weight: 146, tank: 12 },
      { id: 5, name: 'Honda SP 125', brand: 'Honda', price: 0.9, mileage: 60, engine: 124, power: 11, topSpeed: 99, weight: 116, tank: 11 },
      { id: 6, name: 'Hero Splendor Plus', brand: 'Hero', price: 0.75, mileage: 70, engine: 97, power: 8, topSpeed: 87, weight: 112, tank: 10 },
      { id: 7, name: 'Yamaha R15 V4', brand: 'Yamaha', price: 1.85, mileage: 45, engine: 155, power: 18, topSpeed: 140, weight: 142, tank: 11 },
      { id: 8, name: 'Royal Enfield Hunter 350', brand: 'Royal Enfield', price: 1.5, mileage: 36, engine: 349, power: 20, topSpeed: 114, weight: 181, tank: 13 },
      { id: 9, name: 'Triumph Speed 400', brand: 'Triumph', price: 2.4, mileage: 30, engine: 398, power: 40, topSpeed: 160, weight: 176, tank: 13 },
      { id: 10, name: 'Bajaj Pulsar N160', brand: 'Bajaj', price: 1.3, mileage: 45, engine: 164, power: 16, topSpeed: 115, weight: 152, tank: 14 },
    ],
  },

  evCars: {
    label: 'EV Cars',
    fields: [
      { key: 'price', label: 'Price', title: 'Price (₹ lakh)', prefix: '₹', suffix: ' lakh', better: 'low' },
      { key: 'range', label: 'Range', title: 'Range (km)', suffix: ' km', better: 'high' },
      { key: 'battery', label: 'Battery', title: 'Battery (kWh)', suffix: ' kWh', better: 'high' },
      { key: 'power', label: 'Power', title: 'Power (bhp)', suffix: ' bhp', better: 'high' },
      { key: 'charge', label: 'Fast charge 10–80%', title: 'Fast charge (minutes)', suffix: ' min', better: 'low' },
      { key: 'boot', label: 'Boot space', title: 'Boot space (litres)', suffix: ' L', better: 'high' },
    ],
    items: [
      { id: 1, name: 'Tata Nexon EV', brand: 'Tata', price: 14, range: 489, battery: 45, power: 143, charge: 40, boot: 350 },
      { id: 2, name: 'Tata Punch EV', brand: 'Tata', price: 11, range: 421, battery: 35, power: 120, charge: 56, boot: 366 },
      { id: 3, name: 'Tata Curvv EV', brand: 'Tata', price: 18, range: 502, battery: 55, power: 165, charge: 40, boot: 500 },
      { id: 4, name: 'MG Windsor EV', brand: 'MG', price: 14, range: 332, battery: 38, power: 134, charge: 55, boot: 604 },
      { id: 5, name: 'Mahindra BE 6', brand: 'Mahindra', price: 22, range: 682, battery: 79, power: 282, charge: 20, boot: 455 },
      { id: 6, name: 'Mahindra XEV 9e', brand: 'Mahindra', price: 26, range: 656, battery: 79, power: 282, charge: 20, boot: 663 },
      { id: 7, name: 'Hyundai Creta Electric', brand: 'Hyundai', price: 20, range: 473, battery: 51.4, power: 169, charge: 58, boot: 433 },
      { id: 8, name: 'MG ZS EV', brand: 'MG', price: 19, range: 461, battery: 50.3, power: 174, charge: 60, boot: 448 },
      { id: 9, name: 'BYD Atto 3', brand: 'BYD', price: 30, range: 521, battery: 60.5, power: 201, charge: 50, boot: 440 },
      { id: 10, name: 'Maruti e Vitara', brand: 'Maruti', price: 18, range: 500, battery: 61, power: 172, charge: 45, boot: 306 },
    ],
  },

  evBikes: {
    label: 'EV Bikes',
    fields: [
      { key: 'price', label: 'Price', title: 'Price (₹ lakh)', prefix: '₹', suffix: ' lakh', better: 'low' },
      { key: 'range', label: 'Range', title: 'Range (km)', suffix: ' km', better: 'high' },
      { key: 'battery', label: 'Battery', title: 'Battery (kWh)', suffix: ' kWh', better: 'high' },
      { key: 'topSpeed', label: 'Top speed', title: 'Top speed (km/h)', suffix: ' km/h', better: 'high' },
      { key: 'charge', label: 'Home charge 0–80%', title: 'Home charge (hours)', suffix: ' hrs', better: 'low' },
      { key: 'weight', label: 'Weight', title: 'Weight (kg)', suffix: ' kg', better: 'low' },
    ],
    items: [
      { id: 1, name: 'Ola S1 Pro', brand: 'Ola', price: 1.35, range: 195, battery: 4, topSpeed: 120, charge: 6, weight: 116 },
      { id: 2, name: 'Ather 450X', brand: 'Ather', price: 1.5, range: 161, battery: 3.7, topSpeed: 90, charge: 5.5, weight: 108 },
      { id: 3, name: 'TVS iQube', brand: 'TVS', price: 1.3, range: 150, battery: 3.4, topSpeed: 78, charge: 4.5, weight: 118 },
      { id: 4, name: 'Bajaj Chetak', brand: 'Bajaj', price: 1.3, range: 153, battery: 3.5, topSpeed: 73, charge: 3.5, weight: 134 },
      { id: 5, name: 'Ultraviolette F77 Mach 2', brand: 'Ultraviolette', price: 3, range: 323, battery: 10.3, topSpeed: 155, charge: 5.5, weight: 207 },
      { id: 6, name: 'Revolt RV400', brand: 'Revolt', price: 1.3, range: 150, battery: 3.24, topSpeed: 85, charge: 4.5, weight: 108 },
      { id: 7, name: 'Ola Roadster X', brand: 'Ola', price: 1.2, range: 200, battery: 4.5, topSpeed: 118, charge: 7, weight: 125 },
      { id: 8, name: 'Hero Vida V2 Pro', brand: 'Hero', price: 1.2, range: 165, battery: 3.94, topSpeed: 90, charge: 5.5, weight: 125 },
      { id: 9, name: 'Ather Rizta', brand: 'Ather', price: 1.3, range: 160, battery: 3.7, topSpeed: 80, charge: 6, weight: 119 },
      { id: 10, name: 'Ather 450 Apex', brand: 'Ather', price: 1.9, range: 157, battery: 3.7, topSpeed: 100, charge: 5.5, weight: 111 },
    ],
  },
}